# Numpy #

Fundamental library for numerical computing in Python

* Multi-dimensional Arrays and Matrices
* Mathematical Functions
* Performance and Speed
* Integration with other libraries
* Foundation for Scientific Computing

## Numpy Methods

#### Array Creation

- `np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`: Create a NumPy array from an object.
  - data: Input data (list, tuple, etc.)
  - dtype: Desired data type of array (e.g., np.int32, np.float64)
  - copy: If True, the data is copied
  - order: Memory layout order ('C', 'F', 'A', or 'K')
  - subok: If True, subclasses are passed through
  - ndmin: Minimum number of dimensions
- `np.zeros(shape, dtype=float, order='C')`: Create an array of zeros with the specified shape and data type.
  - shape: Shape of the array (tuple)
  - dtype: Desired data type
  - order: Memory layout order ('C' or 'F')
- `np.ones(shape, dtype=float, order='C')`: Create an array of ones with the specified shape and data type.
- `np.full(shape, fill_value, dtype=None, order='C')`: Create an array filled with a specified value.
- `np.empty(shape, dtype=float, order='C')`: Create an empty array with the specified shape and data type.
- `numpy.arange([start,] stop[, step,], dtype=None)`: Returns evenly spaced values within a given interval.
  - start: Start of interval (inclusive, default is 0)
  - stop: End of interval (exclusive)
  - step: Spacing between values (default is 1)
  - dtype: Desired data type
- `numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`: Returns evenly spaced numbers over a specified interval.
  - start: Start of interval
  - stop: End of interval
  - num: Number of samples (default is 50)
  - endpoint: If True, stop is the last sample
  - retstep: If True, return (samples, step)
  - dtype: Desired data type
  - axis: Axis along which the samples are generated

#### Array Manipulation

- `np.reshape(a, newshape, order='C')`: Reshape an array to a new shape.
  - a: Array to be reshaped
  - newshape: Desired shape
  - order: Memory layout order ('C', 'F', 'A')
- `np.resize(a, new_shape)`: Resize an array to a new shape.
- `np.transpose(a, axes=None)`: Transpose an array.
  - a: Input array
  - axes: By default, reverses the dimensions, otherwise permutes them according to the given axes
- `np.flip(a, axis=None)`: Flip an array along a specified axis.
- `np.roll(a, shift, axis=None)`: Roll an array along a specified axis.
- `np.concatenate((a1, a2, ...), axis=0, out=None)`: Joins a sequence of arrays along an existing axis.
  - a1, a2, ...: Sequence of arrays
  - axis: Axis along which arrays will be joined (default is 0)
  - out: If provided, the destination to place the result

#### Indexing and Selection

- `np.where(condition, x, y)`: Select values from two arrays based on a condition.
- `np.take(a, indices, axis=None)`: Select values from an array at specified indices.
- `np.put(a, indices, values, mode='raise')`: Set values in an array at specified indices.

#### Mathematical Operations

- `np.add(x1, x2, out=None)`: Element-wise addition of two arrays.
- `np.subtract(x1, x2, out=None)`: Element-wise subtraction of two arrays.
- `np.multiply(x1, x2, out=None)`: Element-wise multiplication of two arrays.
- `np.divide(x1, x2, out=None)`: Element-wise division of two arrays.
- `np.power(x1, x2, out=None)`: Element-wise exponentiation of two arrays.

#### Statistical Functions

- `np.mean(a, axis=None, dtype=None, out=None, keepdims=False)`: Calculate the mean of an array.
- `np.median(a, axis=None, dtype=None, out=None, keepdims=False)`: Calculate the median of an array.
- `np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)`: Calculate the standard deviation of an array.
- `np.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)`: Calculate the variance of an array.
  - a: Input array
  - axis: Axis along which the means are computed
  - dtype: Desired data type
  - out: Output array
  - keepdims: If True, retains reduced dimensions

#### Linear Algebra

- `np.dot(a, b, out=None)`: Matrix product of two arrays.
- `np.linalg.inv(a)`: Inverse of a matrix.
- `np.linalg.det(a)`: Determinant of a matrix.
- `np.linalg.solve(a, b)`: Solve a system of linear scalar equations.
- `np.linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)`: Computes the singular value decomposition of a matrix.
  - a: Input matrix
  - full_matrices: If True, U and Vh are of shape (M, M) and (N, N)
  - compute_uv: If True, compute U and Vh
  - hermitian: If True, assumes a is Hermitian

#### Random Number Generation

- `np.random.rand(d0, d1, ..., dn)`: Generate an array of random values.
- `np.random.randn(d0, d1, ..., dn)`: Generate an array of random values from a normal distribution.
- `np.random.randint(low, high=None, size=None, dtype='l')`: Generate an array of random integers.

#### Other Functions

- `np.all(a, axis=None, out=None, keepdims=False)`: Test whether all elements of an array are true.
- `np.any(a, axis=None, out=None, keepdims=False)`: Test whether any elements of an array are true.
- `np.sum(a, axis=None, dtype=None, out=None, keepdims=False)`: Calculate the sum of an array.

#### File I/O

- `np.save(file, arr, allow_pickle=True, fix_imports=True)`: Saves an array to a binary file in NumPy .npy format.
  - file: Filename or file object
  - arr: Array to be saved
  - allow_pickle: If True, allows saving object arrays using Python pickles
  - fix_imports: If True, tries to fix the pickle import issue
- `np.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')`: Loads arrays or pickled objects from .npy, .npz or pickled files.
  - file: Filename or file object
  - mmap_mode: Memory-map the file (default is None)
  - allow_pickle: If True, allows loading pickled objects
  - fix_imports: If True, fixes the pickle import issue
  - encoding: What encoding to use when reading Python 2 strings

### Parameters

- a, x1, x2, etc.: Input arrays.
- axis: Axis along which to perform an operation.
- dtype: Data type of the output array.
- out: Output array.
- keepdims: Whether to keep the original dimensions of the input array.
- order: Order of the output array (e.g., 'C' for C-style, 'F' for Fortran-style).
- subok: Whether to return a subclass of ndarray instead of ndarray itself.

# Data Wrangling #

### Transforming raw data into a usable format for analysis ###
* Data Cleaning
* Data Transformation
* Data Enrichment
* Data Standardization
* Data Integration
* Data accuracy
* Data reliability
* Improve performance of ML models
* Enable efficient analysis
* Extract valuable insights

### Data handling Techniques ###
* Parallel computing
* Memory management
* Caching
* Lazy evaluation
* Algorithm Optimization
* Data compression
* Vectorization
* Optimized Libraries

### Vectorization ###
Technique which performs computations on arrays or matrices in an efficient manner

* Hardware-Level Optimization: SIMD
* Low-Level Libraries and BLAS
* Efficient Use of Memory and Caching
* Internal Implementation in High-Level Libraries
* Parallel Processing on GPUs


| Feature | NumPy Array | Python List |
|---------|-------------|-------------|
| Type | Homogeneous (same data type) | Heterogeneous (mixed data types) |
| Memory efficiency | More efficient | Less efficient |
| Speed | Faster for numerical operations | Slower for numerical operations |
| Functionality | Optimized for numerical operations | General-purpose |
| Size | Fixed size | Dynamic size |
| Mutability | Mutable | Mutable |
| Dimensions | Multi-dimensional | One-dimensional (can nest for multi-dimensional) |
| Mathematical operations | Supports vectorized operations | Requires explicit looping |
| Memory layout | Contiguous | Non-contiguous |
| Creation | `np.array([1, 2, 3])` | `[1, 2, 3]` |
| Indexing | Supports advanced indexing | Basic indexing |
| Slicing | Returns a view (memory efficient) | Returns a new list (copy) |
| Broadcasting | Supports broadcasting | No broadcasting |
| Element-wise operations | Built-in support | Requires explicit loops or list comprehensions |
| Memory usage | Lower for large datasets | Higher for large datasets |
| Flexibility | Less flexible (optimized for numerical operations) | More flexible (can store any Python object) |
| Built-in functions | Many scientific computing functions | Basic list operations |
| Performance with large datasets | Excellent | Poor |
| Integration with C/C++ | Easy integration | Requires more work |

In [2]:
import numpy as np

print("NumPy Functions Demonstration")
print("=============================")

# Array Creation
print("\n1. Array Creation")
print("-----------------")
arr = np.array([1, 2, 3, 4, 5])
print("np.array():", arr)

zeros = np.zeros((2, 3))
print("np.zeros():", zeros)

ones = np.ones((2, 2))
print("np.ones():", ones)

full = np.full((2, 2), 7)
print("np.full():", full)

empty = np.empty((2, 2))
print("np.empty():", empty)

arange = np.arange(0, 10, 2)
print("np.arange():", arange)

linspace = np.linspace(0, 1, 5)
print("np.linspace():", linspace)

# Array Manipulation
print("\n2. Array Manipulation")
print("---------------------")
reshaped = np.reshape(arr, (5, 1))
print("np.reshape():", reshaped)

resized = np.resize(arr, (2, 3))
print("np.resize():", resized)

transposed = np.transpose(resized)
print("np.transpose():", transposed)

flipped = np.flip(arr)
print("np.flip():", flipped)

rolled = np.roll(arr, 2)
print("np.roll():", rolled)

concatenated = np.concatenate((arr, arr))
print("np.concatenate():", concatenated)

# Indexing and Selection
print("\n3. Indexing and Selection")
print("-------------------------")
condition = arr > 2
where_result = np.where(condition, arr, arr * 10)
print("np.where():", where_result)

take_result = np.take(arr, [0, 2, 4])
print("np.take():", take_result)

arr_copy = arr.copy()
np.put(arr_copy, [0, 2, 4], [10, 20, 30])
print("np.put():", arr_copy)

# Mathematical Operations
print("\n4. Mathematical Operations")
print("--------------------------")
add_result = np.add(arr, 2)
print("np.add():", add_result)

subtract_result = np.subtract(arr, 2)
print("np.subtract():", subtract_result)

multiply_result = np.multiply(arr, 2)
print("np.multiply():", multiply_result)

divide_result = np.divide(arr, 2)
print("np.divide():", divide_result)

power_result = np.power(arr, 2)
print("np.power():", power_result)

# Statistical Functions
print("\n5. Statistical Functions")
print("------------------------")
mean_result = np.mean(arr)
print("np.mean():", mean_result)

median_result = np.median(arr)
print("np.median():", median_result)

std_result = np.std(arr)
print("np.std():", std_result)

var_result = np.var(arr)
print("np.var():", var_result)

# Linear Algebra
print("\n6. Linear Algebra")
print("-----------------")
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

dot_product = np.dot(a, b)
print("np.dot():", dot_product)

inv_result = np.linalg.inv(a)
print("np.linalg.inv():", inv_result)

det_result = np.linalg.det(a)
print("np.linalg.det():", det_result)

solve_result = np.linalg.solve(a, np.array([1, 2]))
print("np.linalg.solve():", solve_result)

u, s, vh = np.linalg.svd(a)
print("np.linalg.svd(): \nu =", u, ", s =", s, ", vh =", vh)

# Random Number Generation
print("\n7. Random Number Generation")
print("----------------------------")
rand_result = np.random.rand(3, 3)
print("np.random.rand():", rand_result)

randn_result = np.random.randn(3, 3)
print("np.random.randn():", randn_result)

randint_result = np.random.randint(1, 10, size=(3, 3))
print("np.random.randint():", randint_result)

# Other Functions
print("\n8. Other Functions")
print("------------------")
all_result = np.all(arr > 0)
print("np.all():", all_result)

any_result = np.any(arr > 3)
print("np.any():", any_result)

sum_result = np.sum(arr)
print("np.sum():", sum_result)

# File I/O
print("\n9. File I/O")
print("-----------")
np.save('arr.npy', arr)
print("np.save(): Array saved to 'arr.npy'")

loaded_arr = np.load('arr.npy')
print("np.load(): Loaded array:", loaded_arr)

# Clean up
import os
os.remove('arr.npy')
print("Removed 'arr.npy'")

NumPy Functions Demonstration

1. Array Creation
-----------------
np.array(): [1 2 3 4 5]
np.zeros(): [[0. 0. 0.]
 [0. 0. 0.]]
np.ones(): [[1. 1.]
 [1. 1.]]
np.full(): [[7 7]
 [7 7]]
np.empty(): [[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]
np.arange(): [0 2 4 6 8]
np.linspace(): [0.   0.25 0.5  0.75 1.  ]

2. Array Manipulation
---------------------
np.reshape(): [[1]
 [2]
 [3]
 [4]
 [5]]
np.resize(): [[1 2 3]
 [4 5 1]]
np.transpose(): [[1 4]
 [2 5]
 [3 1]]
np.flip(): [5 4 3 2 1]
np.roll(): [4 5 1 2 3]
np.concatenate(): [1 2 3 4 5 1 2 3 4 5]

3. Indexing and Selection
-------------------------
np.where(): [10 20  3  4  5]
np.take(): [1 3 5]
np.put(): [10  2 20  4 30]

4. Mathematical Operations
--------------------------
np.add(): [3 4 5 6 7]
np.subtract(): [-1  0  1  2  3]
np.multiply(): [ 2  4  6  8 10]
np.divide(): [0.5 1.  1.5 2.  2.5]
np.power(): [ 1  4  9 16 25]

5. Statistical Functions
------------------------
np.mean(): 3.0
np.median(): 3.0
np.std(): 1.4142135623730951
np.var()

### Assignment

#### Assignment 1: 
Create a 1D NumPy array with 20 elements, ranging from 0 to 19, using `np.arange()`.

#### Assignment 2: 
Reshape the 1D array into a 4 * 5 2D array. Flatten the 4 * 5 2D array.

**Note:** Don't use Mobile.

#### Assignment 3: 
Create a 3 * 3 matrix of random integers between 1 and 10 using `np.random.randint()`. Transpose the 3 * 3 random integer matrix.

In [ ]:

import numpy as np

# Assignment 1
arr1 = np.arange(0,20)
print(arr1)

# Assignment 2
arr2 = np.reshape(arr1, (4,5))
print(arr2)

# Assignment 3
arr3 = np.random.randint(1,10, (3,3))
print(arr3)
arr3 = arr3.transpose()
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[1 5 3]
 [1 7 5]
 [3 8 7]]
[[1 1 3]
 [5 7 8]
 [3 5 7]]


### Properties of Dataset

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # Output: (2, 3)
print("Size:", arr.size)    # Output: 6
print("Dtype:", arr.dtype)  # Output: int64
print("Itemsize:", arr.itemsize)  # Output: 8 (assuming 64-bit integers)
print("Ndim:", arr.ndim)    # Output: 2
print("Flags:", arr.flags)
```

### Assignment: Understanding Array Dimensions and Shapes

- Create a 1D, 2D, and 3D array using NumPy.

- For each array, print the `ndim` and `shape` properties.

- Write a function `describe_array(arr)` that takes a NumPy array and prints its `ndim`, `shape`, `size`, and `dtype`.

In [ ]:
def describe_arr(arr):
    print("Shape:", arr.shape)
    print("Size:", arr.size)
    print("Dtype:", arr.dtype)
    print("Itemsize:", arr.itemsize)
    print("Ndim:", arr.ndim)
    print("Flags:", arr.flags)
    print()

arr1 = np.array([1, 2, 3] )
describe_arr(arr1)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
describe_arr(arr2)
arr3 = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10,11,12]]])
describe_arr(arr3)

Shape: (3,)
Size: 3
Dtype: int64
Itemsize: 8
Ndim: 1
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False


Shape: (2, 3)
Size: 6
Dtype: int64
Itemsize: 8
Ndim: 2
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False


Shape: (2, 2, 3)
Size: 12
Dtype: int64
Itemsize: 8
Ndim: 3
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False




### Assignment: Exploring Data Types and Memory Consumption

- Create an array with different data types: integers, floats, and booleans.

- Compare their `itemsize` and `nbytes` to understand the memory requirements for each data type.

- Change the `dtype` of an existing array from `int` to `float` and verify the changes in `itemsize` and `nbytes`.

In [ ]:
def describe_arr_type_memory(arr):
    print(arr)
    print("Dtype:", arr.dtype)
    print("Itemsize:", arr.itemsize)
    print("No. Bytes:", arr.nbytes)
    print()

arr1 = np.array([1, 2, 3], int)
describe_arr_type_memory(arr1)
arr2 = arr1.astype(float)
describe_arr_type_memory(arr2)
arr3 = arr1.astype(bool)
describe_arr_type_memory(arr3)

[1 2 3]
Dtype: int64
Itemsize: 8
No. Bytes: 24

[1. 2. 3.]
Dtype: float64
Itemsize: 8
No. Bytes: 24

[ True  True  True]
Dtype: bool
Itemsize: 1
No. Bytes: 3



### Indexing Operations 

In [ ]:
import numpy as np

print("NumPy Array Accessing and Slicing Examples")
print("==========================================")

# 1D Array
print("\n1. 1D Array")
print("-----------")
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original 1D array:", arr_1d)

# Basic indexing
print("arr_1d[0]:", arr_1d[0])  # Output: 0
print("arr_1d[-1]:", arr_1d[-1])  # Output: 9

# Slicing
print("arr_1d[2:5]:", arr_1d[2:5])  # Output: [2 3 4]
print("arr_1d[:5]:", arr_1d[:5])  # Output: [0 1 2 3 4]
print("arr_1d[5:]:", arr_1d[5:])  # Output: [5 6 7 8 9]
print("arr_1d[::2]:", arr_1d[::2])  # Output: [0 2 4 6 8]
print("arr_1d[::-1]:", arr_1d[::-1])  # Output: [9 8 7 6 5 4 3 2 1 0]

# 2D Array
print("\n2. 2D Array")
print("-----------")
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("Original 2D array:")
print(arr_2d)

# Basic indexing
print("arr_2d[0, 0]:", arr_2d[0, 0])  # Output: 1
print("arr_2d[2, 3]:", arr_2d[2, 3])  # Output: 12

# Slicing rows
print("arr_2d[1]:", arr_2d[1])  # Output: [5 6 7 8]
print("arr_2d[0:2]:")
print(arr_2d[0:2])  # Output: [[1 2 3 4]
                    #          [5 6 7 8]]

# Slicing columns
print("arr_2d[:, 1]:", arr_2d[:, 1])  # Output: [ 2  6 10]
print("arr_2d[:, 1:3]:")
print(arr_2d[:, 1:3])  # Output: [[ 2  3]
                       #          [ 6  7]
                       #          [10 11]]

# Mixed slicing
print("arr_2d[0:2, 1:3]:")
print(arr_2d[0:2, 1:3])  # Output: [[2 3]
                         #          [6 7]]

# Stepped slicing
print("arr_2d[::2, ::2]:")
print(arr_2d[::2, ::2])  # Output: [[ 1  3]
                         #          [ 9 11]]

# 3D Array
print("\n3. 3D Array")
print("-----------")
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]],
                   [[9, 10], [11, 12]]])
print("Original 3D array:")
print(arr_3d)

# Basic indexing
print("arr_3d[0, 0, 0]:", arr_3d[0, 0, 0])  # Output: 1
print("arr_3d[2, 1, 1]:", arr_3d[2, 1, 1])  # Output: 12

# Slicing in 3D
print("arr_3d[1]:")
print(arr_3d[1])  # Output: [[5 6]
                  #          [7 8]]

print("arr_3d[:, 1]:")
print(arr_3d[:, 1])  # Output: [[ 3  4]
                     #          [ 7  8]
                     #          [11 12]]

print("arr_3d[:, :, 1]:")
print(arr_3d[:, :, 1])  # Output: [[ 2  4]
                        #          [ 6  8]
                        #          [10 12]]

# Complex slicing in 3D
print("arr_3d[0:2, :, 1]:")
print(arr_3d[0:2, :, 1])  # Output: [[2 4]
                          #          [6 8]]

print("arr_3d[:, 1:, :1]:")
print(arr_3d[:, 1:, :1])  # Output: [[[3]]
                          #          [[7]]
                          #          [[11]]]

# Boolean indexing
print("\n4. Boolean Indexing")
print("-------------------")
bool_idx = arr_1d > 5
print("Boolean index (arr_1d > 5):", bool_idx)
# Output: [False False False False False False  True  True  True  True]

print("arr_1d[arr_1d > 5]:", arr_1d[arr_1d > 5])  # Output: [6 7 8 9]

# Fancy indexing
print("\n5. Fancy Indexing")
print("------------------")
fancy_idx = np.array([0, 2, -1])
print("Fancy index:", fancy_idx)

print("arr_1d[fancy_idx]:", arr_1d[fancy_idx])  # Output: [0 2 9]

print("arr_2d[[0, 2], [1, 3]]:", arr_2d[[0, 2], [1, 3]])  # Output: [ 2 12]

NumPy Array Accessing and Slicing Examples

1. 1D Array
-----------
Original 1D array: [0 1 2 3 4 5 6 7 8 9]
arr_1d[0]: 0
arr_1d[-1]: 9
arr_1d[2:5]: [2 3 4]
arr_1d[:5]: [0 1 2 3 4]
arr_1d[5:]: [5 6 7 8 9]
arr_1d[::2]: [0 2 4 6 8]
arr_1d[::-1]: [9 8 7 6 5 4 3 2 1 0]

2. 2D Array
-----------
Original 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr_2d[0, 0]: 1
arr_2d[2, 3]: 12
arr_2d[1]: [5 6 7 8]
arr_2d[0:2]:
[[1 2 3 4]
 [5 6 7 8]]
arr_2d[:, 1]: [ 2  6 10]
arr_2d[:, 1:3]:
[[ 2  3]
 [ 6  7]
 [10 11]]
arr_2d[0:2, 1:3]:
[[2 3]
 [6 7]]
arr_2d[::2, ::2]:
[[ 1  3]
 [ 9 11]]

3. 3D Array
-----------
Original 3D array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
arr_3d[0, 0, 0]: 1
arr_3d[2, 1, 1]: 12
arr_3d[1]:
[[5 6]
 [7 8]]
arr_3d[:, 1]:
[[ 3  4]
 [ 7  8]
 [11 12]]
arr_3d[:, :, 1]:
[[ 2  4]
 [ 6  8]
 [10 12]]
arr_3d[0:2, :, 1]:
[[2 4]
 [6 8]]
arr_3d[:, 1:, :1]:
[[[ 3]]

 [[ 7]]

 [[11]]]

4. Boolean Indexing
-------------------
Boolean index (arr_1d > 5): [Fal

### Assignment: Manipulating Subarrays

- Create a 2D array of shape (5, 5) filled with random integers between 50 and 100.

- Replace the central 3x3 subarray with zeroes.

- Print the modified array and explain the slicing used to access and modify the subarray.


In [ ]:
import numpy as np

arr3 = np.random.randint(50,100, (5,5))


arr3[1:-1:, 1:-1:]= np.zeros((3,3))
# arr3[1:-1:, 1:-1:]=0

print(arr3)

[[61 70 54 89 83]
 [83  0  0  0 65]
 [97  0  0  0 71]
 [77  0  0  0 58]
 [89 77 67 89 80]]


### Assignment 7: Transposition and Mean Calculation

- Create a 2D array representing a dataset with 5 rows (samples) and 3 columns (features). Each element should be a random integer between 10 and 100.

- Use transposition to switch rows with columns, converting the array into 3 rows and 5 columns.

- Compute and compare the mean of the original and transposed datasets along both axes.

In [ ]:
import numpy as np

dataset = np.random.randint(10, 101, (5, 3))

print("Original dataset:\n", dataset)

# transposed_dataset = np.transpose(dataset)
transposed_dataset = dataset.T

print("Transposed dataset:\n", transposed_dataset)

original_means = dataset.mean(axis=0)
transposed_means = transposed_dataset.mean(axis=0)

print("\nMeans along axis 0 (columns) of the original dataset:\n", original_means)
print("Means along axis 0 (columns) of the transposed dataset:\n", transposed_means)

original_means_rows = dataset.mean(axis=1)
transposed_means_rows = transposed_dataset.mean(axis=1)

print("\nMeans along axis 1 (rows) of the original dataset:\n", original_means_rows)
print("Means along axis 1 (rows) of the transposed dataset:\n", transposed_means_rows)

Original dataset:
 [[38 60 77]
 [70 94 76]
 [27 99 66]
 [37 86 47]
 [90 36 56]]
Transposed dataset:
 [[38 70 27 37 90]
 [60 94 99 86 36]
 [77 76 66 47 56]]

Means along axis 0 (columns) of the original dataset:
 [52.4 75.  64.4]
Means along axis 0 (columns) of the transposed dataset:
 [58.33333333 80.         64.         56.66666667 60.66666667]

Means along axis 1 (rows) of the original dataset:
 [58.33333333 80.         64.         56.66666667 60.66666667]
Means along axis 1 (rows) of the transposed dataset:
 [52.4 75.  64.4]


### Assignment 8: Handling Complex CSV Data

- Create a CSV file named `data_complex.csv` with the following contents, using semicolons as delimiters and some lines as comments:

```csv
        #This is a comment line
        1.0; 2.0; 3.0
        #Another comment
        4.0; 5.0; 6.0
        7.0; 8.0; 9.0
```

- Use `np.genfromtxt()` to load the data, specifying the delimiter as a semicolon and ignoring lines that start with a `#`.

- Print the loaded array and ensure the comments are ignored.

In [ ]:

import csv
import numpy as np

csv_data = """
# This is a comment line
1.0; 2.0; 3.0
# Another comment
4.0; 5.0; 6.0
7.0; 8.0; 9.0
"""

try:
    with open('data_complex.csv', 'w', newline='') as csvfile:
        csvfile.write(csv_data)
    print("CSV data written successfully.")
except Exception as e:
    print("Error writing CSV data:", e)

# Read the CSV data into a NumPy array
filename = 'data_complex.csv'

try:
    data = np.genfromtxt(filename, delimiter=';', comments='#')
    print("CSV data read successfully:")
    print(data)
except Exception as e:
    print("Error reading CSV data:", e)

CSV data written successfully.
CSV data read successfully:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Assignment 9: Square Root Calculation

- **Description:** Create a NumPy array with values ranging from 1 to 16. Compute the square root of each element in the array.

- **Square root calculation:** `np.sqrt(array)`

- **CSV File Creation:** Save the original array and the computed square roots to a CSV named `square_root_results.csv`.

- **To save contents to a file:**

    `np.savetxt('filename', array, delimiter='')`

- **Format the text file to save:**

    `np.savetxt('filename', np.column_stack((OGarray, NEW_ARRAY)), delimiter=',', header='Original, Square Root', comments="", fmt='%d, %.2f')`

In [ ]:
import numpy as np
import csv

filename = 'square_root_results.csv'
arr = np.random.randint(1,16,(3,3))
sqrt_arr = np.sqrt(arr)
print(arr, sqrt_arr,sep='\n')

np.savetxt(filename, arr, delimiter=';')

try:
    with open(filename , 'r') as file:
        print(file.read())
except Exception as e:
    print("Error writing CSV data:", e)

[[ 8 10  4]
 [15  7  6]
 [12 14  9]]
[[2.82842712 3.16227766 2.        ]
 [3.87298335 2.64575131 2.44948974]
 [3.46410162 3.74165739 3.        ]]
8.000000000000000000e+00;1.000000000000000000e+01;4.000000000000000000e+00
1.500000000000000000e+01;7.000000000000000000e+00;6.000000000000000000e+00
1.200000000000000000e+01;1.400000000000000000e+01;9.000000000000000000e+00



### Assignment 10: Matrix Multiplication and Transposition

- Create two matrices of size 4x2 and 2x3.

- Multiply these matrices using `np.matmul()`.

- Transpose the result using `.T`.

- Print the matrices, the result of multiplication, and the transposed result.

In [ ]:

import numpy as np

arr1 = np.random.randint(1,10,(4,2))
arr2 = np.random.randint(1,10,(2,3))

arr3 = np.matmul(arr1,arr2)
print(arr3)

arr3 = arr3.T
print(arr3)

[[36 25 53]
 [44 39 67]
 [64 55 97]
 [46 52 73]]
[[36 44 64 46]
 [25 39 55 52]
 [53 67 97 73]]


### Home Assignment 1: Compute Eigenvalues and Eigenvectors of a Given Matrix and Save Results to a CSV File

- Create a square matrix (e.g., 3x3) with arbitrary values.

- Compute the eigenvalues and eigenvectors of the matrix using `np.linalg.eig()`.

- Save the eigenvalues and eigenvectors to a CSV file. Use formatting.

In [1]:
import numpy as np

arr = np.random.randint(1, 10, (3, 3))

eigenvalues, eigenvectors = np.linalg.eig(arr)

combined = np.column_stack((eigenvalues, eigenvectors))

filename = 'eigenvalue_eigenvector.csv'
np.savetxt(filename, combined, delimiter=',',
           header='Eigenvalues, Eigenvector1, Eigenvector2, Eigenvector3',
           comments='# This CSV contains eigenvalues and eigenvectors\n',
           fmt='%f')

try:
    with open(filename , 'r') as file:
        print(file.read())
except Exception as e:
    print("Error writing CSV data:", e)

# This CSV contains eigenvalues and eigenvectors
Eigenvalues, Eigenvector1, Eigenvector2, Eigenvector3
 (16.405386+0.000000j), (0.570371+0.000000j), (0.079520-0.469735j), (0.079520+0.469735j)
 (-1.202693+2.239380j), (0.681490+0.000000j), (-0.653602+0.000000j), (-0.653602-0.000000j)
 (-1.202693-2.239380j), (0.458528+0.000000j), (0.488276+0.327745j), (0.488276-0.327745j)

